name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        scalaVersion: ['2.12.13', '2.13.5', '3.0.0-RC2']
        javaTag: ['8u282', '11.0.10', '16', '11.0.10-oraclelinux8', 'graalvm-ce-21.0.0-java11', 'graalvm-ce-21.0.0-java8']
        include:
          - javaTag: '8u282'
            dockerContext: 'debian'
            baseImageTag: '8u282-jdk-buster'
          - javaTag: '11.0.10'
            dockerContext: 'debian'
            baseImageTag: '11.0.10-jdk-buster'
          - javaTag: '16'
            dockerContext: 'debian'
            baseImageTag: '16-jdk-buster'
          - javaTag: '11.0.10-oraclelinux8'
            dockerContext: 'oracle'
            baseImageTag: '11.0.10-jdk-oraclelinux8'
          - javaTag: 'graalvm-ce-21.0.0-java11'
            dockerContext: 'graalvm-ce'
            baseImageTag: 'java11-21.0.0'
          - javaTag: 'graalvm-ce-21.0.0-java8'
            dockerContext: 'graalvm-ce'
            baseImageTag: 'java8-21.0.0'
          - scalaVersion: '2.11.12'
            javaTag: '8u282'
            dockerContext: 'debian'
            baseImageTag: '8u282-jdk-buster'
    steps:
    - uses: actions/checkout@v1
    - name: Get latest SBT version
      id: get_sbt_version
      run: |
        SBT_VERSION=$(
          curl -s curl -L https://github.com/sbt/sbt/releases |
          grep -i -w 'sbt-[0-9]*\.[0-9]*\.[0-9]*\.tgz' -o |
          grep -i -w '[0-9]*\.[0-9]*\.[0-9]*' -o |
          sort -V | tail -n 1)
        echo ::set-output name=VERSION::$SBT_VERSION
    - name: Create docker tag
      id: create_docker_tag
      run: |
        TAG=hseeberger/scala-sbt:${{ matrix.javaTag }}_${{ steps.get_sbt_version.outputs.VERSION }}_${{ matrix.scalaVersion }}
        echo ::set-output name=TAG::$TAG
    - name: Build docker image
      run: |
        docker build ${{ matrix.dockerContext }} \
            --no-cache \
            -t "${{ steps.create_docker_tag.outputs.TAG }}" \
            --build-arg BASE_IMAGE_TAG=${{ matrix.baseImageTag }} \
            --build-arg SBT_VERSION=${{ steps.get_sbt_version.outputs.VERSION }} \
            --build-arg SCALA_VERSION=${{ matrix.scalaVersion }}
    - name: Push image to DockerHub
      if: github.event_name != 'pull_request'
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u hseeberger --password-stdin
        docker push ${{ steps.create_docker_tag.outputs.TAG }}
